from typing import TypedDict, Optional
from langgraph.graph import StateGraph, END
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.language_models import BaseChatModel

# --- Import your LLMs ---
from langchain_anthropic import ChatAnthropic
from langchain_google_genai import ChatGoogleGenerativeAI

from src.config import settings
from src.tools.clickup import create_clickup_task
from src.tools.github import post_github_comment

# --- 1. Define Graph State (Simplified) ---
class PRWorkflowState(TypedDict):
    """The state passed between nodes in our graph."""
    # Input from webhook
    pr_title: str
    pr_url: str
    pr_branch: str
    pr_body: Optional[str]  # <--- ADD THIS LINE
    
    # Generated by nodes
    task_name: Optional[str]
    task_description: Optional[str]
    clickup_task_url: Optional[str]
    final_comment: Optional[str]

# --- 2. Initialize LLM (Selector) ---

def get_llm() -> BaseChatModel:
    """
    Factory function to get the LLM based on settings.
    """
    provider = settings.LLM_PROVIDER.lower()
    
    if provider == "claude":
        print("--- Initializing LLM: Claude ---")
        if not settings.ANTHROPIC_API_KEY:
            raise ValueError("LLM_PROVIDER is 'claude' but ANTHROPIC_API_KEY is not set.")
        return ChatAnthropic(model="claude-3-haiku-20240307", api_key=settings.ANTHROPIC_API_KEY)
    
    elif provider == "gemini":
        print("--- Initializing LLM: Gemini ---")
        if not settings.GOOGLE_API_KEY:
            raise ValueError("LLM_PROVIDER is 'gemini' but GOOGLE_API_KEY is not set.")
        # Use the latest stable model
        return ChatGoogleGenerativeAI(model="gemini-2.5-flash", google_api_key=settings.GOOGLE_API_KEY)
    
    raise ValueError(f"Unsupported LLM_PROVIDER: {settings.LLM_PROVIDER}. Must be 'gemini' or 'claude'.")

# Get the LLM instance to be used by the graph
llm = get_llm()


# --- 3. Define Graph Nodes (Updated) ---

def node_generate_task_details(state: PRWorkflowState) -> dict:
    """Uses the LLM to generate a clean task name."""
    print("\n--- NODE: Generating Task Details ---")
    
    prompt = ChatPromptTemplate.from_messages([
        ("system", "You are a project manager. Your job is to create a concise, clear task name for a ClickUp task based on a GitHub PR title. Output ONLY the task name."),
        ("human", "PR Title: {title}\n\nTask Name:"),
    ])
    
    chain = prompt | llm
    task_name = chain.invoke({
        "title": state["pr_title"]
    }).content.strip().replace('"', '')

    # --- THIS IS THE MODIFIED PART ---
    pr_body = state.get("pr_body")
    if not pr_body: # Handle empty/null descriptions
        pr_body = "No description provided."

    # Create a richer description
    task_description = (
        f"Please review the following PR:\n"
        f"PR Link: {state['pr_url']}\n\n"
        f"--- PR Description ---\n"
        f"{pr_body}"
    )
    # --- END OF MODIFIED PART ---
    
    print(f"Generated Task Name: {task_name}")
    return {"task_name": task_name, "task_description": task_description}

def node_create_task(state: PRWorkflowState) -> dict:
    """Calls the ClickUp tool to create the review task."""
    print("\n--- NODE: Creating ClickUp task ---")
    
    task_url = create_clickup_task.invoke({
        "task_name": state['task_name'],
        "description": state['task_description'],
    })
    
    return {"clickup_task_url": task_url}

def node_post_comment(state: PRWorkflowState) -> dict:
    """Posts a final confirmation comment back to the GitHub PR."""
    print("\n--- NODE: Posting GitHub comment ---")
    
    comment = f"🤖 PR-to-Task bot: I've created a ClickUp task for this review: {state['clickup_task_url']}"
    
    post_github_comment.invoke({
        "pr_url": state["pr_url"],
        "comment_body": comment
    })
    
    return {"final_comment": comment}

# --- 4. Assemble the Graph (Updated) ---

print("Building simplified LangGraph workflow...")
workflow = StateGraph(PRWorkflowState)

# Add nodes
workflow.add_node("generate_task_details", node_generate_task_details)
workflow.add_node("create_task", node_create_task)
workflow.add_node("post_comment", node_post_comment)

# Define the new linear flow
workflow.set_entry_point("generate_task_details")
workflow.add_edge("generate_task_details", "create_task")
workflow.add_edge("create_task", "post_comment")
workflow.add_edge("post_comment", END)

app_runnable = workflow.compile()
print("LangGraph workflow compiled successfully.")